# Permalinks
permalink:           /:title/

# Setup
title:               "Varun Yellina"
tagline:             "@vyellina"
url:                 http://yellina.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Varun Yellina
  url:               https://twitter.com/vyellina
  email:             varun@yellina.io

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/varunyellina/poole

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
